# Generated by Django 3.2.9 on 2021-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
    ]
